server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leo
    username: leo
    password: leo
    host: 192.168.130.100

leo:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: leo
    verifyCodeTemplate: SMS_148614415
